import { Platform } from 'react-native';

// AUTO-GENERATED BY scripts/start-dev.js
export const LOCAL_IP = '192.168.1.101'; 

export const API_URL = `http://${LOCAL_IP}:3001/api`;
export const SOCKET_URL = `http://${LOCAL_IP}:3001`;

export const MOCK_TOKEN = 'mock-auth-token-123';
