const { execSync, spawn } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');

// Helper to find local IPv4
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  for (let iface in interfaces) {
    for (let details of interfaces[iface]) {
      if (details.family === 'IPv4' && !details.internal) {
        return details.address;
      }
    }
  }
  return '127.0.0.1';
}

function updateFrontendConstants() {
  const localIP = getLocalIP();
  console.log(`📡 Auto-detected local IP: ${localIP}`);
  const constantsPath = path.resolve(__dirname, '../mobile/utils/constants.ts');
  const content = `import { Platform } from 'react-native';

// AUTO-GENERATED BY scripts/start-dev.js
export const LOCAL_IP = '${localIP}'; 

export const API_URL = \`http://\${LOCAL_IP}:3001/api\`;
export const SOCKET_URL = \`http://\${LOCAL_IP}:3001\`;

export const MOCK_TOKEN = 'mock-auth-token-123';
`;
  fs.writeFileSync(constantsPath, content);
  console.log('✅ Updated mobile/utils/constants.ts with current IP.');
}

function killPort(port) {
  try {
    const pids = execSync(`lsof -ti:${port}`).toString().trim().split('\n');
    pids.forEach(pid => {
      if (pid) {
        console.log(`🔪 Killing process ${pid} on port ${port}...`);
        process.kill(pid, 'SIGKILL');
      }
    });
  } catch (e) {
    // Port not in use, fine.
  }
}

async function start() {
  console.log('🚀 Starting Unico Monorepo Dev Environment...\n');

  // Step 1: Validate Env
  try {
    execSync('npx tsx scripts/validate-env.ts', { stdio: 'inherit' });
  } catch (e) {
    process.exit(1);
  }

  // Step 2: Fix Port Conflict
  killPort(3001);

  // Step 3: Update Frontend URL
  updateFrontendConstants();

  // Step 4: Generate Client & Start
  const concurrently = require('concurrently');

  const { result } = concurrently([
    { 
       command: 'cd server && npx prisma generate && npm run dev', 
       name: 'SERVER', 
       prefixColor: 'cyan' 
    },
    { 
       command: 'cd mobile && npx expo start --lan --clear', 
       name: 'EXPO', 
       prefixColor: 'magenta' 
    }
  ], {
    killOthers: ['failure', 'success'],
  });

  // Step 5: Health Check Loop
  setTimeout(() => {
    console.log('\n🏥 Performing Health Check...');
    const http = require('http');
    http.get('http://localhost:3001/health', (res) => {
      if (res.statusCode === 200) {
        console.log('🎉 Backend is HEALTHY and running at :3001');
      } else {
        console.log(`⚠️ Backend returned status ${res.statusCode}.`);
      }
    }).on('error', (err) => {
      console.log('⚠️ Health check failed to reach server yet: ' + err.message);
    });
  }, 10000); // Check after 10s

  result.then(() => {}, (err) => {
    console.error('❌ One of the processes failed. System exited.');
  });
}

start();
